### ISSUE TITLE
Approve/disapprove emails

### ISSUE THREAD

**Issue by venkatarun95** [kunaaljain/gems#12]
Emails must be sent (or a suggestion must be made to the administrator) when a candidate is approved or disapproved.

This can be done by a simple popup that asks (suggests) the admin to send an email. This can be the stopgap solution until the ability to send emails is perfected.

**Comment by kunaaljain** [comment]
These things will be perfected if we use IITG mail server. Till then populate the mails to a google spreadsheet. I have written a script which will send the mail by take message from appropriate columns.

**Comment by venkatarun95** [comment]
True. But we cannot use bulk mailing here as this involves emailing one candidate only. here we can simply suggest the admin to send a personalized email (we can always provide a template) and the admin sends using his/her normal email id the traditional way.
